// <auto-generated />
using GrammarService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GrammarService.Migrations
{
    [DbContext(typeof(GrammarContext))]
    partial class GrammarContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("GrammarService.Models.Grammar", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartSymbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Grammars");
                });

            modelBuilder.Entity("GrammarService.Models.Production", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GrammarId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NonTerminal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RightSide")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GrammarId");

                    b.ToTable("Productions");
                });

            modelBuilder.Entity("GrammarService.Models.Production", b =>
                {
                    b.HasOne("GrammarService.Models.Grammar", "Grammar")
                        .WithMany("Productions")
                        .HasForeignKey("GrammarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grammar");
                });

            modelBuilder.Entity("GrammarService.Models.Grammar", b =>
                {
                    b.Navigation("Productions");
                });
#pragma warning restore 612, 618
        }
    }
}
